#!/usr/bin/env bash
echo "Installer for version 1.2.1"
echo "dd and lsblk are required."
sudo cp usbtool.sh "/usr/local/bin/usbtool"
sudo chmod +x "/usr/local/bin/usbtool"
echo "Done!"
echo "Run the command 'usbtool' to run the app"